### ISSUE TITLE
starknet object does not exist in known properties

### ISSUE THREAD

**Issue by ankitchiplunkar** [Shard-Labs/starknet-hardhat-example#18]
I have installed the plugin and also added it in the hardhat.config.ts file but still seeing this error
```
Type '{ defaultNetwork: string; gasReporter: { currency: string; enabled: boolean; excludeContracts: never[]; src: string; }; networks: { hardhat: { accounts: { mnemonic: string; }; chainId: number; }; goerli: NetworkUserConfig; kovan: NetworkUserConfig; rinkeby: NetworkUserConfig; ropsten: NetworkUserConfig; }; paths: { ...' is not assignable to type 'HardhatUserConfig'.
 

 Object literal may only specify known properties, and 'starknet' does not exist in type 'HardhatUserConfig'.ts(2322)
  ```

**Comment by FabijanC** [comment]
Which `starknet-hardhat-plugin` version are you using? Some breaking changes were introduced with plugin v0.4.0, be sure to check them: https://github.com/Shard-Labs/starknet-hardhat-plugin/releases/tag/v0.4.0

**Comment by ankitchiplunkar** [comment]
hey, I am just using the latest master from this repo and trying to run tests

**Comment by ankitchiplunkar** [comment]
removed node_modules and tried again, still the same issue.
were you folks able to reproduce the problem?

**Comment by FabijanC** [comment]
not able to reproduce it, @dribeiro-ShardLabs what do you think?

**Comment by dribeiro-ShardLabs** [comment]
Hi, can you share the package.json and packagelock.json files? Also, try running npm update. I remember someone having a similar issue and it was due to the hardhat version they were using.

**Comment by ankitchiplunkar** [comment]
ok, I think I found the issue, I tried installing packages via `yarn install` and it was not working but when I tried `npm install` the issue was not there anymore

**Comment by dribeiro-ShardLabs** [comment]
Thank you for your feedback :) we will reference this issue in the Readme.
