### ISSUE TITLE
Running the tests gives an error `error TS2339: Property 'getPredeployedAccounts' does not exist on type 'Devnet'.`

### ISSUE THREAD

**Issue by amanusk** [Shard-Labs/starknet-hardhat-example#70]
Steps:
* Clone Repo
* Run `npm install`
* Run devent in a separate terminal
* Run tests with `npm run test`

Get an error
```An unexpected error occurred:

test/get-predeployed-accounts.test.ts:9:48 - error TS2339: Property 'getPredeployedAccounts' does not exist on type 'Devnet'.

9         const response = await starknet.devnet.getPredeployedAccounts();
                                                 ~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by FabijanC** [comment]
Thanks for noticing this. This test file was supposed to be included in this example repository only with the next plugin version, which will support the `getPredeployedAccounts` function. So this will probably be fixed when starknet-hardhat-plugin v0.6.1 is released.

**Comment by FabijanC** [comment]
This PR introduces the required function: https://github.com/Shard-Labs/starknet-hardhat-plugin/pull/125
It should be merged tomorrow or the day after.

**Comment by FabijanC** [comment]
Fixed with https://github.com/Shard-Labs/starknet-hardhat-example/commit/d829dcdd168029d5e39762f16bec76716b604cd0
