### ISSUE TITLE
Invalid Starknet function call: __init__()

### ISSUE THREAD

**Issue by ahmetoznar** [Shard-Labs/starknet-hardhat-example#87]
I have been facing with following issue while testing, this happened after upgrading version to latest.
I already have defined the required parameters in .env but still i have this error. 

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/45452358/209825505-4b0523f6-6bac-433e-8b3b-18ca95209f7f.png">

**Comment by FabijanC** [comment]
@ahmetoznar are you still getting this?

**Comment by FabijanC** [comment]
Closing as stale.
