### ISSUE TITLE
StarknetPluginError: Could not perform call on getPublicKey.

### ISSUE THREAD

**Issue by lsbyerley** [Shard-Labs/starknet-hardhat-example#98]
When attempting to run `npx hardhat test test/quick-test.ts`, I am getting the following error:

```
StarknetPluginError: Could not perform call on getPublicKey.
Got BadRequest while trying to access http://host.docker.internal:5050/feeder_gateway/call_contract?blockNumber=pending. Status code: 500; text: {"code":"StarknetErrorCode.UNINITIALIZED_CONTRACT","message":"Requested contract address 0x000 is not deployed."}
```

I have set the `OZ_ACCOUNT_ADDRESS` and the `OZ_ACCOUNT_PRIVATE_KEY` in the `.env` file to a starknet account on testnet. Is there another step i'm missing?

**Comment by FabijanC** [comment]
Providing the exact command, the exact error message, and the exact config file is usually necessary for debugging. In this case, we're missing your hardhat config file (hardhat.config.ts).

**Comment by FabijanC** [comment]
The error indicates that you are using a local network, whereas your bug report mentions an account deployed on testnet. It could be that you are using integrated-devnet as your [configured network](https://shard-labs.github.io/starknet-hardhat-plugin/docs/intro/#runtime-network).

**Comment by FabijanC** [comment]
In the link I provided above, you can see how you can specify `alpha-goerli` or `devnet`. The runtime network can be specified both via the `network:` property and by supplying `--starknet-network <NETWORK_NAME>` to `npx hardhat test`.

But integrated-devnet can be really useful, as its a hardhat-wrapper of starknet-devnet, whose features can be found [here](https://shard-labs.github.io/starknet-devnet/docs/guide/run).

**Comment by lsbyerley** [comment]
@FabijanC awesome thanks!
